FROM ubuntu:latest

RUN apt-get update && apt-get install -y \
    build-essential \
    libssl-dev \
    libffi-dev \
    zlib1g-dev \
    git

WORKDIR /usr/src
RUN git clone https://github.com/nishu-builder/cpython.git

WORKDIR /usr/src/cpython
RUN ./configure
RUN make && make install

# Keep the container running
CMD ["tail", "-f", "/dev/null"]
